# Generated by Django 5.1.4 on 2025-06-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_two', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Emial',
            new_name='email',
        ),
    ]
