# Generated by Django 5.1.4 on 2025-06-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='porfile_pic',
            new_name='profile_pic',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='porfolio_site',
            new_name='profolio_site',
        ),
    ]
